version: '3.8'

services:
  mysql:
    container_name: mysql-server
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - common

  redis:
    container_name: redis-server
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./data/redis/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --requirepass '${REDIS_PASSWORD}' --appendonly yes --save "" --protected-mode no --dir /data
    networks:
      - common

networks:
  common:
    driver: bridge
